services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/setup_database.sql
